### ISSUE TITLE
`tailwindcss: {},` missing in postcss config

### ISSUE THREAD

**Issue by indistinctchatter** [kirbyschool/kirby-merkurkit#1]
The tailwind does not build properly when used as a template out of the box,
while it takes typography.css classes in consideration, it purges every other utility class used in e.g. `default.php` template.

I believe it’s the postcss config (`postcss.config.js`) missing line `tailwindcss: {},`

(this part of the config gets mentioned in Kirbyschool video `07 Setting up Kirby build process 3 TailwindCSS ` at ~23:20, where `tailwindcss: {},` follows the line `'postcss-nesting': {}`, or another option `'tailwindcss/nesting': 'postcss-nesting',`)

I also experienced `Error: Cannot find module 'postcss-nesting'` caused by the missing dependency `postcss-nesting` (removed in the lesson if 'tailwindcss/nesting': 'postcss-nesting', is used as tailwind already carries it as dependecy too) . May be worth re-checking how that works for others and keep it in the package for the future students.

**Comment by iskrisis** [comment]
Fixed with last version
